### Test Full Batch (155 logs)
POST http://127.0.0.1:8000/api/log
Content-Type: application/json

{
  "data": [
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "25",
        "memory_mb.keyword": "25",
        "name": "lsass.exe",
        "name.keyword": "lsass.exe",
        "path": "C:\\Windows\\System32\\lsass.exe",
        "path.keyword": "C:\\Windows\\System32\\lsass.exe",
        "pid": "1356",
        "pid.keyword": "1356"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "29",
        "memory_mb.keyword": "29",
        "name": "svchost.exe",
        "name.keyword": "svchost.exe",
        "path": "C:\\Windows\\System32\\svchost.exe",
        "path.keyword": "C:\\Windows\\System32\\svchost.exe",
        "pid": "1496",
        "pid.keyword": "1496"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "1",
        "memory_mb.keyword": "1",
        "name": "fontdrvhost.exe",
        "name.keyword": "fontdrvhost.exe",
        "path": "C:\\Windows\\System32\\fontdrvhost.exe",
        "path.keyword": "C:\\Windows\\System32\\fontdrvhost.exe",
        "pid": "1528",
        "pid.keyword": "1528"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "18",
        "memory_mb.keyword": "18",
        "name": "svchost.exe",
        "name.keyword": "svchost.exe",
        "path": "C:\\Windows\\System32\\svchost.exe",
        "path.keyword": "C:\\Windows\\System32\\svchost.exe",
        "pid": "1620",
        "pid.keyword": "1620"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "8",
        "memory_mb.keyword": "8",
        "name": "svchost.exe",
        "name.keyword": "svchost.exe",
        "path": "C:\\Windows\\System32\\svchost.exe",
        "path.keyword": "C:\\Windows\\System32\\svchost.exe",
        "pid": "1676",
        "pid.keyword": "1676"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "10",
        "memory_mb.keyword": "10",
        "name": "svchost.exe",
        "name.keyword": "svchost.exe",
        "path": "C:\\Windows\\System32\\svchost.exe",
        "path.keyword": "C:\\Windows\\System32\\svchost.exe",
        "pid": "1880",
        "pid.keyword": "1880"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "7",
        "memory_mb.keyword": "7",
        "name": "svchost.exe",
        "name.keyword": "svchost.exe",
        "path": "C:\\Windows\\System32\\svchost.exe",
        "path.keyword": "C:\\Windows\\System32\\svchost.exe",
        "pid": "1896",
        "pid.keyword": "1896"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "4",
        "memory_mb.keyword": "4",
        "name": "svchost.exe",
        "name.keyword": "svchost.exe",
        "path": "C:\\Windows\\System32\\svchost.exe",
        "path.keyword": "C:\\Windows\\System32\\svchost.exe",
        "pid": "1904",
        "pid.keyword": "1904"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "8",
        "memory_mb.keyword": "8",
        "name": "svchost.exe",
        "name.keyword": "svchost.exe",
        "path": "C:\\Windows\\System32\\svchost.exe",
        "path.keyword": "C:\\Windows\\System32\\svchost.exe",
        "pid": "936",
        "pid.keyword": "936"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "6",
        "memory_mb.keyword": "6",
        "name": "svchost.exe",
        "name.keyword": "svchost.exe",
        "path": "C:\\Windows\\System32\\svchost.exe",
        "path.keyword": "C:\\Windows\\System32\\svchost.exe",
        "pid": "1420",
        "pid.keyword": "1420"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "2",
        "memory_mb.keyword": "2",
        "name": "IntelCpHDCPSvc.exe",
        "name.keyword": "IntelCpHDCPSvc.exe",
        "path": "C:\\Windows\\System32\\DriverStore\\FileRepository\\iigd_dch.inf_amd64_51f685305808e3a5\\IntelCpHDCPSvc.exe",
        "path.keyword": "C:\\Windows\\System32\\DriverStore\\FileRepository\\iigd_dch.inf_amd64_51f685305808e3a5\\IntelCpHDCPSvc.exe",
        "pid": "1204",
        "pid.keyword": "1204"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "12",
        "memory_mb.keyword": "12",
        "name": "svchost.exe",
        "name.keyword": "svchost.exe",
        "path": "C:\\Windows\\System32\\svchost.exe",
        "path.keyword": "C:\\Windows\\System32\\svchost.exe",
        "pid": "2056",
        "pid.keyword": "2056"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "6",
        "memory_mb.keyword": "6",
        "name": "svchost.exe",
        "name.keyword": "svchost.exe",
        "path": "C:\\Windows\\System32\\svchost.exe",
        "path.keyword": "C:\\Windows\\System32\\svchost.exe",
        "pid": "2064",
        "pid.keyword": "2064"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "9",
        "memory_mb.keyword": "9",
        "name": "svchost.exe",
        "name.keyword": "svchost.exe",
        "path": "C:\\Windows\\System32\\svchost.exe",
        "path.keyword": "C:\\Windows\\System32\\svchost.exe",
        "pid": "2204",
        "pid.keyword": "2204"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "9",
        "memory_mb.keyword": "9",
        "name": "svchost.exe",
        "name.keyword": "svchost.exe",
        "path": "C:\\Windows\\System32\\svchost.exe",
        "path.keyword": "C:\\Windows\\System32\\svchost.exe",
        "pid": "2212",
        "pid.keyword": "2212"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "3",
        "memory_mb.keyword": "3",
        "name": "IntelCpHeciSvc.exe",
        "name.keyword": "IntelCpHeciSvc.exe",
        "path": "C:\\Windows\\System32\\DriverStore\\FileRepository\\iigd_dch.inf_amd64_51f685305808e3a5\\IntelCpHeciSvc.exe",
        "path.keyword": "C:\\Windows\\System32\\DriverStore\\FileRepository\\iigd_dch.inf_amd64_51f685305808e3a5\\IntelCpHeciSvc.exe",
        "pid": "2384",
        "pid.keyword": "2384"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "16",
        "memory_mb.keyword": "16",
        "name": "svchost.exe",
        "name.keyword": "svchost.exe",
        "path": "C:\\Windows\\System32\\svchost.exe",
        "path.keyword": "C:\\Windows\\System32\\svchost.exe",
        "pid": "2392",
        "pid.keyword": "2392"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "3",
        "memory_mb.keyword": "3",
        "name": "svchost.exe",
        "name.keyword": "svchost.exe",
        "path": "C:\\Windows\\System32\\svchost.exe",
        "path.keyword": "C:\\Windows\\System32\\svchost.exe",
        "pid": "2440",
        "pid.keyword": "2440"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "1620",
        "pid.keyword": "1620",
        "port": "135",
        "port.keyword": "135",
        "protocol": "6",
        "protocol.keyword": "6"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "4",
        "pid.keyword": "4",
        "port": "445",
        "port.keyword": "445",
        "protocol": "6",
        "protocol.keyword": "6"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "7560",
        "pid.keyword": "7560",
        "port": "902",
        "port.keyword": "902",
        "protocol": "6",
        "protocol.keyword": "6"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "7560",
        "pid.keyword": "7560",
        "port": "912",
        "port.keyword": "912",
        "protocol": "6",
        "protocol.keyword": "6"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "4",
        "pid.keyword": "4",
        "port": "1462",
        "port.keyword": "1462",
        "protocol": "6",
        "protocol.keyword": "6"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "8212",
        "pid.keyword": "8212",
        "port": "5040",
        "port.keyword": "5040",
        "protocol": "6",
        "protocol.keyword": "6"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "4",
        "pid.keyword": "4",
        "port": "5357",
        "port.keyword": "5357",
        "protocol": "6",
        "protocol.keyword": "6"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "5800",
        "pid.keyword": "5800",
        "port": "7680",
        "port.keyword": "7680",
        "protocol": "6",
        "protocol.keyword": "6"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "1356",
        "pid.keyword": "1356",
        "port": "49664",
        "port.keyword": "49664",
        "protocol": "6",
        "protocol.keyword": "6"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "1192",
        "pid.keyword": "1192",
        "port": "49665",
        "port.keyword": "49665",
        "protocol": "6",
        "protocol.keyword": "6"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "2056",
        "pid.keyword": "2056",
        "port": "49666",
        "port.keyword": "49666",
        "protocol": "6",
        "protocol.keyword": "6"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "3000",
        "pid.keyword": "3000",
        "port": "49667",
        "port.keyword": "49667",
        "protocol": "6",
        "protocol.keyword": "6"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "4772",
        "pid.keyword": "4772",
        "port": "49668",
        "port.keyword": "49668",
        "protocol": "6",
        "protocol.keyword": "6"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "1336",
        "pid.keyword": "1336",
        "port": "49670",
        "port.keyword": "49670",
        "protocol": "6",
        "protocol.keyword": "6"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "18768",
        "pid.keyword": "18768",
        "port": "123",
        "port.keyword": "123",
        "protocol": "17",
        "protocol.keyword": "17"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "7948",
        "pid.keyword": "7948",
        "port": "500",
        "port.keyword": "500",
        "protocol": "17",
        "protocol.keyword": "17"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "6772",
        "pid.keyword": "6772",
        "port": "3702",
        "port.keyword": "3702",
        "protocol": "17",
        "protocol.keyword": "17"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "6772",
        "pid.keyword": "6772",
        "port": "3702",
        "port.keyword": "3702",
        "protocol": "17",
        "protocol.keyword": "17"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "7948",
        "pid.keyword": "7948",
        "port": "4500",
        "port.keyword": "4500",
        "protocol": "17",
        "protocol.keyword": "17"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "8212",
        "pid.keyword": "8212",
        "port": "5050",
        "port.keyword": "5050",
        "protocol": "17",
        "protocol.keyword": "17"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "2936",
        "pid.keyword": "2936",
        "port": "5353",
        "port.keyword": "5353",
        "protocol": "17",
        "protocol.keyword": "17"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "2936",
        "pid.keyword": "2936",
        "port": "5355",
        "port.keyword": "5355",
        "protocol": "17",
        "protocol.keyword": "17"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "3152",
        "pid.keyword": "3152",
        "port": "41641",
        "port.keyword": "41641",
        "protocol": "17",
        "protocol.keyword": "17"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "2936",
        "pid.keyword": "2936",
        "port": "49995",
        "port.keyword": "49995",
        "protocol": "17",
        "protocol.keyword": "17"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "2936",
        "pid.keyword": "2936",
        "port": "52565",
        "port.keyword": "52565",
        "protocol": "17",
        "protocol.keyword": "17"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "6772",
        "pid.keyword": "6772",
        "port": "53307",
        "port.keyword": "53307",
        "protocol": "17",
        "protocol.keyword": "17"
      }
    },
    {
      "name": "listening_ports",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "address": "0.0.0.0",
        "address.keyword": "0.0.0.0",
        "pid": "8184",
        "pid.keyword": "8184",
        "port": "62683",
        "port.keyword": "62683",
        "protocol": "17",
        "protocol.keyword": "17"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "MSI App Player",
        "name.keyword": "MSI App Player",
        "publisher": "BlueStack Systems, Inc.",
        "publisher.keyword": "BlueStack Systems, Inc.",
        "version": "4.200.0.6306",
        "version.keyword": "4.200.0.6306"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Microsoft SQL Server 2022 (64-bit)",
        "name.keyword": "Microsoft SQL Server 2022 (64-bit)"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Microsoft SQL Server 2022 (64-bit)",
        "name.keyword": "Microsoft SQL Server 2022 (64-bit)",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Norton Security",
        "name.keyword": "Norton Security",
        "publisher": "Gen Digital Inc.",
        "publisher.keyword": "Gen Digital Inc.",
        "version": "25.11.10580.2110",
        "version.keyword": "25.11.10580.2110"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Microsoft 365 Apps for enterprise - en-us",
        "name.keyword": "Microsoft 365 Apps for enterprise - en-us",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.19328.20244",
        "version.keyword": "16.0.19328.20244"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Microsoft OneDrive",
        "name.keyword": "Microsoft OneDrive",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "25.209.1026.0002",
        "version.keyword": "25.209.1026.0002"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 Database Engine Services",
        "name.keyword": "SQL Server 2022 Database Engine Services",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Python 3.13.9 Executables (64-bit)",
        "name.keyword": "Python 3.13.9 Executables (64-bit)",
        "publisher": "Python Software Foundation",
        "publisher.keyword": "Python Software Foundation",
        "version": "3.13.9150.0",
        "version.keyword": "3.13.9150.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "WD_BLACK AN1500",
        "name.keyword": "WD_BLACK AN1500",
        "publisher": "ENE TECHNOLOGY INC.",
        "publisher.keyword": "ENE TECHNOLOGY INC.",
        "version": "1.0.12.0",
        "version.keyword": "1.0.12.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Intel(R) Serial IO",
        "name.keyword": "Intel(R) Serial IO",
        "publisher": "Intel Corporation",
        "publisher.keyword": "Intel Corporation",
        "version": "30.100.2020.7",
        "version.keyword": "30.100.2020.7"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 SQL Diagnostics",
        "name.keyword": "SQL Server 2022 SQL Diagnostics",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Python 3.12.5 Standard Library (64-bit)",
        "name.keyword": "Python 3.12.5 Standard Library (64-bit)",
        "publisher": "Python Software Foundation",
        "publisher.keyword": "Python Software Foundation",
        "version": "3.12.5150.0",
        "version.keyword": "3.12.5150.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Microsoft ODBC Driver 17 for SQL Server",
        "name.keyword": "Microsoft ODBC Driver 17 for SQL Server",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "17.10.6.1",
        "version.keyword": "17.10.6.1"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Python 3.13.9 Test Suite (64-bit)",
        "name.keyword": "Python 3.13.9 Test Suite (64-bit)",
        "publisher": "Python Software Foundation",
        "publisher.keyword": "Python Software Foundation",
        "version": "3.13.9150.0",
        "version.keyword": "3.13.9150.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 Shared Management Objects",
        "name.keyword": "SQL Server 2022 Shared Management Objects",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "RstDowngradeGuard",
        "name.keyword": "RstDowngradeGuard",
        "publisher": "Intel Corporation",
        "publisher.keyword": "Intel Corporation",
        "version": "18.0.0.0",
        "version.keyword": "18.0.0.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 Database Engine Shared",
        "name.keyword": "SQL Server 2022 Database Engine Shared",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "ENE_DRAM_RGB_AIO",
        "name.keyword": "ENE_DRAM_RGB_AIO",
        "publisher": "Ene Tech.",
        "publisher.keyword": "Ene Tech.",
        "version": "1.0.3.9",
        "version.keyword": "1.0.3.9"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "ENE_X-JMI_HAL",
        "name.keyword": "ENE_X-JMI_HAL",
        "publisher": "ENE Tech",
        "publisher.keyword": "ENE Tech",
        "version": "1.0.5.1",
        "version.keyword": "1.0.5.1"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Python 3.13.9 pip Bootstrap (64-bit)",
        "name.keyword": "Python 3.13.9 pip Bootstrap (64-bit)",
        "publisher": "Python Software Foundation",
        "publisher.keyword": "Python Software Foundation",
        "version": "3.13.9150.0",
        "version.keyword": "3.13.9150.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Python 3.13.9 Core Interpreter (64-bit)",
        "name.keyword": "Python 3.13.9 Core Interpreter (64-bit)",
        "publisher": "Python Software Foundation",
        "publisher.keyword": "Python Software Foundation",
        "version": "3.13.9150.0",
        "version.keyword": "3.13.9150.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 Shared Management Objects Extensions",
        "name.keyword": "SQL Server 2022 Shared Management Objects Extensions",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "ENE_EHD_M2_HAL",
        "name.keyword": "ENE_EHD_M2_HAL",
        "publisher": "ENE TECHNOLOGY INC.",
        "publisher.keyword": "ENE TECHNOLOGY INC.",
        "version": "1.0.9.0",
        "version.keyword": "1.0.9.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "vs_communityx64msi",
        "name.keyword": "vs_communityx64msi",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "17.14.36025",
        "version.keyword": "17.14.36025"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Python 3.12.5 Documentation (64-bit)",
        "name.keyword": "Python 3.12.5 Documentation (64-bit)",
        "publisher": "Python Software Foundation",
        "publisher.keyword": "Python Software Foundation",
        "version": "3.12.5150.0",
        "version.keyword": "3.12.5150.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "VMware Workstation",
        "name.keyword": "VMware Workstation",
        "publisher": "VMware, Inc.",
        "publisher.keyword": "VMware, Inc.",
        "version": "17.5.2",
        "version.keyword": "17.5.2"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 Database Engine Services",
        "name.keyword": "SQL Server 2022 Database Engine Services",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.44.35211",
        "name.keyword": "Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.44.35211",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "14.44.35211",
        "version.keyword": "14.44.35211"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Python 3.13.9 Documentation (64-bit)",
        "name.keyword": "Python 3.13.9 Documentation (64-bit)",
        "publisher": "Python Software Foundation",
        "publisher.keyword": "Python Software Foundation",
        "version": "3.13.9150.0",
        "version.keyword": "3.13.9150.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Intel(R) Chipset Device Software",
        "name.keyword": "Intel(R) Chipset Device Software",
        "publisher": "Intel Corporation",
        "publisher.keyword": "Intel Corporation",
        "version": "10.1.18383.8213",
        "version.keyword": "10.1.18383.8213"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Python 3.12.5 Executables (64-bit)",
        "name.keyword": "Python 3.12.5 Executables (64-bit)",
        "publisher": "Python Software Foundation",
        "publisher.keyword": "Python Software Foundation",
        "version": "3.12.5150.0",
        "version.keyword": "3.12.5150.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "vs_minshellx64msi",
        "name.keyword": "vs_minshellx64msi",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "17.14.36301",
        "version.keyword": "17.14.36301"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Python 3.13.9 Add to Path (64-bit)",
        "name.keyword": "Python 3.13.9 Add to Path (64-bit)",
        "publisher": "Python Software Foundation",
        "publisher.keyword": "Python Software Foundation",
        "version": "3.13.9150.0",
        "version.keyword": "3.13.9150.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 DMF",
        "name.keyword": "SQL Server 2022 DMF",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Microsoft SQL Server 2022 RsFx Driver",
        "name.keyword": "Microsoft SQL Server 2022 RsFx Driver",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 Database Engine Services",
        "name.keyword": "SQL Server 2022 Database Engine Services",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 Common Files",
        "name.keyword": "SQL Server 2022 Common Files",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Microsoft Visual Studio Installer",
        "name.keyword": "Microsoft Visual Studio Installer",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "3.14.2086.54749",
        "version.keyword": "3.14.2086.54749"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 Shared Management Objects",
        "name.keyword": "SQL Server 2022 Shared Management Objects",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Microsoft OLE DB Driver for SQL Server",
        "name.keyword": "Microsoft OLE DB Driver for SQL Server",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "18.7.4.0",
        "version.keyword": "18.7.4.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 Connection Info",
        "name.keyword": "SQL Server 2022 Connection Info",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 Batch Parser",
        "name.keyword": "SQL Server 2022 Batch Parser",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Python 3.13.9 Tcl/Tk Support (64-bit)",
        "name.keyword": "Python 3.13.9 Tcl/Tk Support (64-bit)",
        "publisher": "Python Software Foundation",
        "publisher.keyword": "Python Software Foundation",
        "version": "3.13.9150.0",
        "version.keyword": "3.13.9150.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Microsoft Visual C++ 2022 X64 Additional Runtime - 14.44.35211",
        "name.keyword": "Microsoft Visual C++ 2022 X64 Additional Runtime - 14.44.35211",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "14.44.35211",
        "version.keyword": "14.44.35211"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "OptaneDowngradeGuard",
        "name.keyword": "OptaneDowngradeGuard",
        "publisher": "Intel Corporation",
        "publisher.keyword": "Intel Corporation",
        "version": "18.0.0.0",
        "version.keyword": "18.0.0.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 Common Files",
        "name.keyword": "SQL Server 2022 Common Files",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Python 3.13.9 Standard Library (64-bit)",
        "name.keyword": "Python 3.13.9 Standard Library (64-bit)",
        "publisher": "Python Software Foundation",
        "publisher.keyword": "Python Software Foundation",
        "version": "3.13.9150.0",
        "version.keyword": "3.13.9150.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Office 16 Click-to-Run Licensing Component",
        "name.keyword": "Office 16 Click-to-Run Licensing Component",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.19029.20208",
        "version.keyword": "16.0.19029.20208"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Office 16 Click-to-Run Extensibility Component",
        "name.keyword": "Office 16 Click-to-Run Extensibility Component",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.19328.20106",
        "version.keyword": "16.0.19328.20106"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Office 16 Click-to-Run Localization Component",
        "name.keyword": "Office 16 Click-to-Run Localization Component",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.13127.20616",
        "version.keyword": "16.0.13127.20616"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 XEvent",
        "name.keyword": "SQL Server 2022 XEvent",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "ENE_MousePad_HAL",
        "name.keyword": "ENE_MousePad_HAL",
        "publisher": "ENE TECHNOLOGY INC.",
        "publisher.keyword": "ENE TECHNOLOGY INC.",
        "version": "1.0.2.0",
        "version.keyword": "1.0.2.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Intel(R) Serial IO",
        "name.keyword": "Intel(R) Serial IO",
        "publisher": "Intel Corporation",
        "publisher.keyword": "Intel Corporation",
        "version": "30.100.2020.7",
        "version.keyword": "30.100.2020.7"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 Shared Management Objects Extensions",
        "name.keyword": "SQL Server 2022 Shared Management Objects Extensions",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Python 3.12.5 Development Libraries (64-bit)",
        "name.keyword": "Python 3.12.5 Development Libraries (64-bit)",
        "publisher": "Python Software Foundation",
        "publisher.keyword": "Python Software Foundation",
        "version": "3.12.5150.0",
        "version.keyword": "3.12.5150.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Microsoft Teams Meeting Add-in for Microsoft Office",
        "name.keyword": "Microsoft Teams Meeting Add-in for Microsoft Office",
        "publisher": "Microsoft",
        "publisher.keyword": "Microsoft",
        "version": "1.25.18302",
        "version.keyword": "1.25.18302"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Microsoft VSS Writer for SQL Server 2022",
        "name.keyword": "Microsoft VSS Writer for SQL Server 2022",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Python 3.12.5 Core Interpreter (64-bit)",
        "name.keyword": "Python 3.12.5 Core Interpreter (64-bit)",
        "publisher": "Python Software Foundation",
        "publisher.keyword": "Python Software Foundation",
        "version": "3.12.5150.0",
        "version.keyword": "3.12.5150.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA Graphics Driver 511.65",
        "name.keyword": "NVIDIA Graphics Driver 511.65",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "511.65",
        "version.keyword": "511.65"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA GeForce Experience 3.20.4.14",
        "name.keyword": "NVIDIA GeForce Experience 3.20.4.14",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "3.20.4.14",
        "version.keyword": "3.20.4.14"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA PhysX System Software 9.20.0221",
        "name.keyword": "NVIDIA PhysX System Software 9.20.0221",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "9.20.0221",
        "version.keyword": "9.20.0221"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA SHIELD Streaming",
        "name.keyword": "NVIDIA SHIELD Streaming",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "7.1.28594849",
        "version.keyword": "7.1.28594849"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA Install Application",
        "name.keyword": "NVIDIA Install Application",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "2.1002.363.0",
        "version.keyword": "2.1002.363.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA ABHub",
        "name.keyword": "NVIDIA ABHub",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "14.3.61.0",
        "version.keyword": "14.3.61.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA Backend",
        "name.keyword": "NVIDIA Backend",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "38.0.5.0",
        "version.keyword": "38.0.5.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA Container",
        "name.keyword": "NVIDIA Container",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "1.27",
        "version.keyword": "1.27"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA TelemetryApi helper for NvContainer",
        "name.keyword": "NVIDIA TelemetryApi helper for NvContainer",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "1.27",
        "version.keyword": "1.27"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA LocalSystem Container",
        "name.keyword": "NVIDIA LocalSystem Container",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "1.27",
        "version.keyword": "1.27"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA Message Bus for NvContainer",
        "name.keyword": "NVIDIA Message Bus for NvContainer",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "1.27",
        "version.keyword": "1.27"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVAPI Monitor plugin for NvContainer",
        "name.keyword": "NVAPI Monitor plugin for NvContainer",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "1.27",
        "version.keyword": "1.27"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA NetworkService Container",
        "name.keyword": "NVIDIA NetworkService Container",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "1.27",
        "version.keyword": "1.27"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA Session Container",
        "name.keyword": "NVIDIA Session Container",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "1.27",
        "version.keyword": "1.27"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA User Container",
        "name.keyword": "NVIDIA User Container",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "1.27",
        "version.keyword": "1.27"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NvModuleTracker",
        "name.keyword": "NvModuleTracker",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "6.14.24033.38719",
        "version.keyword": "6.14.24033.38719"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA NodeJS",
        "name.keyword": "NVIDIA NodeJS",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "3.20.4.14",
        "version.keyword": "3.20.4.14"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA Platform Controllers and Framework",
        "name.keyword": "NVIDIA Platform Controllers and Framework",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "457.43",
        "version.keyword": "457.43"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA Watchdog Plugin for NvContainer",
        "name.keyword": "NVIDIA Watchdog Plugin for NvContainer",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "1.27",
        "version.keyword": "1.27"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA Telemetry Client",
        "name.keyword": "NVIDIA Telemetry Client",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "14.3.61.0",
        "version.keyword": "14.3.61.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA Virtual Host Controller",
        "name.keyword": "NVIDIA Virtual Host Controller",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "3.04.0.1",
        "version.keyword": "3.04.0.1"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Nvidia Share",
        "name.keyword": "Nvidia Share",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "3.20.4.14",
        "version.keyword": "3.20.4.14"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA ShadowPlay 3.20.4.14",
        "name.keyword": "NVIDIA ShadowPlay 3.20.4.14",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "3.20.4.14",
        "version.keyword": "3.20.4.14"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA SHIELD Wireless Controller Driver",
        "name.keyword": "NVIDIA SHIELD Wireless Controller Driver",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "3.20.4.8",
        "version.keyword": "3.20.4.8"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA Update Core",
        "name.keyword": "NVIDIA Update Core",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "38.0.5.0",
        "version.keyword": "38.0.5.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "NVIDIA Virtual Audio 4.13.0.0",
        "name.keyword": "NVIDIA Virtual Audio 4.13.0.0",
        "publisher": "NVIDIA Corporation",
        "publisher.keyword": "NVIDIA Corporation",
        "version": "4.13.0.0",
        "version.keyword": "4.13.0.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "vs_minshellinteropx64msi",
        "name.keyword": "vs_minshellinteropx64msi",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "17.14.36015",
        "version.keyword": "17.14.36015"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Safe Exam Browser (x64)",
        "name.keyword": "Safe Exam Browser (x64)",
        "publisher": "ETH Z\u00fcrich",
        "publisher.keyword": "ETH Z\u00fcrich",
        "version": "3.9.0.787",
        "version.keyword": "3.9.0.787"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 XEvent",
        "name.keyword": "SQL Server 2022 XEvent",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "WD_BLACK D50",
        "name.keyword": "WD_BLACK D50",
        "publisher": "ENE TECHNOLOGY INC.",
        "publisher.keyword": "ENE TECHNOLOGY INC.",
        "version": "1.0.9.0",
        "version.keyword": "1.0.9.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Microsoft SQL Server 2022 Setup (English)",
        "name.keyword": "Microsoft SQL Server 2022 Setup (English)",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Python 3.12.5 Test Suite (64-bit)",
        "name.keyword": "Python 3.12.5 Test Suite (64-bit)",
        "publisher": "Python Software Foundation",
        "publisher.keyword": "Python Software Foundation",
        "version": "3.12.5150.0",
        "version.keyword": "3.12.5150.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Python 3.12.5 Tcl/Tk Support (64-bit)",
        "name.keyword": "Python 3.12.5 Tcl/Tk Support (64-bit)",
        "publisher": "Python Software Foundation",
        "publisher.keyword": "Python Software Foundation",
        "version": "3.12.5150.0",
        "version.keyword": "3.12.5150.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Python 3.12.5 pip Bootstrap (64-bit)",
        "name.keyword": "Python 3.12.5 pip Bootstrap (64-bit)",
        "publisher": "Python Software Foundation",
        "publisher.keyword": "Python Software Foundation",
        "version": "3.12.5150.0",
        "version.keyword": "3.12.5150.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 Database Engine Services",
        "name.keyword": "SQL Server 2022 Database Engine Services",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Microsoft Update Health Tools",
        "name.keyword": "Microsoft Update Health Tools",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "5.72.0.0",
        "version.keyword": "5.72.0.0"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "DiagnosticsHub_CollectionService",
        "name.keyword": "DiagnosticsHub_CollectionService",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "17.14.36412",
        "version.keyword": "17.14.36412"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 Database Engine Shared",
        "name.keyword": "SQL Server 2022 Database Engine Shared",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 DMF",
        "name.keyword": "SQL Server 2022 DMF",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "Tailscale",
        "name.keyword": "Tailscale",
        "publisher": "Tailscale Inc.",
        "publisher.keyword": "Tailscale Inc.",
        "version": "1.90.8",
        "version.keyword": "1.90.8"
      }
    },
    {
      "name": "programs",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "name": "SQL Server 2022 Connection Info",
        "name.keyword": "SQL Server 2022 Connection Info",
        "publisher": "Microsoft Corporation",
        "publisher.keyword": "Microsoft Corporation",
        "version": "16.0.1000.6",
        "version.keyword": "16.0.1000.6"
      }
    },
    {
      "name": "patches",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "hotfix_id": "KB5066131",
        "hotfix_id.keyword": "KB5066131",
        "installed_on": "10/20/2025",
        "installed_on.keyword": "10/20/2025"
      }
    },
    {
      "name": "patches",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "hotfix_id": "KB5068861",
        "hotfix_id.keyword": "KB5068861",
        "installed_on": "11/23/2025",
        "installed_on.keyword": "11/23/2025"
      }
    },
    {
      "name": "patches",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "hotfix_id": "KB5067035",
        "hotfix_id.keyword": "KB5067035",
        "installed_on": "11/5/2025",
        "installed_on.keyword": "11/5/2025"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "129",
        "memory_mb.keyword": "129",
        "name": "Registry",
        "name.keyword": "Registry",
        "path": "Registry",
        "path.keyword": "Registry",
        "pid": "224",
        "pid.keyword": "224"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "0",
        "memory_mb.keyword": "0",
        "name": "smss.exe",
        "name.keyword": "smss.exe",
        "path": "C:\\Windows\\System32\\smss.exe",
        "path.keyword": "C:\\Windows\\System32\\smss.exe",
        "pid": "796",
        "pid.keyword": "796"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "5",
        "memory_mb.keyword": "5",
        "name": "csrss.exe",
        "name.keyword": "csrss.exe",
        "path": "C:\\Windows\\System32\\csrss.exe",
        "path.keyword": "C:\\Windows\\System32\\csrss.exe",
        "pid": "1084",
        "pid.keyword": "1084"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "5",
        "memory_mb.keyword": "5",
        "name": "wininit.exe",
        "name.keyword": "wininit.exe",
        "path": "C:\\Windows\\System32\\wininit.exe",
        "path.keyword": "C:\\Windows\\System32\\wininit.exe",
        "pid": "1192",
        "pid.keyword": "1192"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "11",
        "memory_mb.keyword": "11",
        "name": "services.exe",
        "name.keyword": "services.exe",
        "path": "C:\\Windows\\System32\\services.exe",
        "path.keyword": "C:\\Windows\\System32\\services.exe",
        "pid": "1336",
        "pid.keyword": "1336"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "0",
        "memory_mb.keyword": "0",
        "name": "[System Process]",
        "name.keyword": "[System Process]",
        "pid": "0",
        "pid.keyword": "0"
      }
    },
    {
      "name": "process_status",
      "hostname": "MSI",
      "unixTime": 1764230829,
      "columns": {
        "cpu_seconds": "0",
        "cpu_seconds.keyword": "0",
        "memory_mb": "3",
        "memory_mb.keyword": "3",
        "name": "System",
        "name.keyword": "System",
        "pid": "4",
        "pid.keyword": "4"
      }
    }
  ]
}